<#
.SYNOPSIS
  Deploy the checked-out branch on the Windows box (spec §2). Replaces the macOS
  `npm run build && launchctl kickstart ...` step.
.DESCRIPTION
  Refuses to restart while an attended session the server spawned is alive, or a user_chrome
  run is running (restarting pm2 would kill the claude child it launched). -Force skips the guard.
  Steps: git pull --ff-only -> npm ci -> npm run build -> pm2 restart sortie -> wait for the API.
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File C:\sortie\ops\windows\deploy.ps1
  powershell -ExecutionPolicy Bypass -File C:\sortie\ops\windows\deploy.ps1 -Force
#>
[CmdletBinding()]
param(
  [switch]$Force,
  # Repo root. Resolved in the body, not here: with [CmdletBinding()] the automatic variables
  # $PSScriptRoot / $PSCommandPath / $MyInvocation.MyCommand.Path are all EMPTY inside param()
  # default expressions when the script runs via `powershell -File` (seen 2026-09-11, and again
  # 2026-09-13 from Git Bash), so a default computed here always threw "Split-Path: Path is null".
  [string]$Root,
  [string]$Base = "http://127.0.0.1:3000"
)
$ErrorActionPreference = "Stop"

if (-not $Root) {
  # In the body the automatic variables are populated. The process command line's -File argument is
  # the last-resort fallback: it is always there when launched as `powershell -File <script>`.
  $scriptPath = $PSCommandPath
  if (-not $scriptPath) { $scriptPath = $MyInvocation.MyCommand.Path }
  if (-not $scriptPath) {
    $cl = [Environment]::GetCommandLineArgs()
    for ($i = 0; $i -lt $cl.Length - 1; $i++) { if ($cl[$i] -ieq "-File" -or $cl[$i] -ieq "-f") { $scriptPath = $cl[$i + 1]; break } }
  }
  if (-not $scriptPath) { throw "cannot locate deploy.ps1 (no PSCommandPath and no -File on the command line); pass -Root <repo>" }
  $Root = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent ((Resolve-Path -LiteralPath $scriptPath).Path)))
}
Set-Location $Root

# The status/dispatch routes need the box's internal token since accounts landed (2026-09-13):
# <DATA_DIR>/internal-token, generated by the server on first boot (or SORTIE_INTERNAL_TOKEN in
# .env). Read per call, not once: on the deploy that introduces accounts the file only appears
# after the restart, and the post-restart poll must pick it up.
$dataDir = Join-Path $Root "data"
$envFile = Join-Path $Root ".env"
if (Test-Path $envFile) {
  $m = Select-String -Path $envFile -Pattern '^\s*DATA_DIR\s*=\s*(.+?)\s*$' | Select-Object -First 1
  if ($m) { $dataDir = $m.Matches[0].Groups[1].Value.Trim('"').Trim("'") }
}
$tokenFile = Join-Path $dataDir "internal-token"
function Get-AuthHeaders {
  if (Test-Path $tokenFile) { return @{ authorization = "Bearer " + (Get-Content $tokenFile -Raw).Trim() } }
  return @{}
}
function Get-Json($url) {
  try { return Invoke-RestMethod -Uri $url -TimeoutSec 5 -Headers (Get-AuthHeaders) } catch { return $null }
}

if (-not $Force) {
  $attended = Get-Json "$Base/api/executor/dispatch"
  $status = Get-Json "$Base/api/executor/status"
  $spawn = $null
  if ($attended) { $spawn = $attended.spawn }
  $spawnAlive = [bool]($spawn -and $spawn.alive)
  $running = @()
  if ($status -and $status.runs) {
    $running = @($status.runs | Where-Object { $_.channel -eq "user_chrome" -and $_.status -eq "running" })
  }
  if ($spawnAlive -or $running.Count -gt 0) {
    # Say what is holding the deploy, so a stale record can be told from real work (2026-09-22:
    # the guard refused all evening on a session that had nothing to do). The server's own view:
    # GET /api/executor/dispatch -> spawn.busy (runs / forms it filled awaiting the user / stale
    # cards from earlier sessions) and spawn.idleSec (reaped at 15 min).
    Write-Host "Refusing to deploy: attended work in progress." -ForegroundColor Yellow
    if ($spawnAlive) {
      $reach = "reachable"
      if (-not $spawn.reachable) { $reach = "NOT reachable from the current server process (it restarted after the spawn)" }
      $idle = "not idle"
      if ($null -ne $spawn.idleSec) { $idle = "idle for $([math]::Round($spawn.idleSec / 60)) min (the dispatcher reaps it at 15)" }
      Write-Host "  spawned session: pid $($spawn.pid), started for run #$($spawn.runId) at $($spawn.startedAt); $reach; $idle" -ForegroundColor Yellow
      $b = $spawn.busy
      if ($b) {
        $runs = @($b.runs)
        $runsText = "none"
        if ($runs.Count -gt 0) { $runsText = ($runs | ForEach-Object { "#$($_.id) $($_.kind) $($_.status)" }) -join ", " }
        $w = $b.waiting
        $held = [int]$w.awaiting_confirm + [int]$w.needs_info + [int]$w.prepared
        Write-Host "    holding it: runs running/queued: $runsText; forms it filled awaiting the user: awaiting_confirm $($w.awaiting_confirm), needs_info $($w.needs_info), prepared $($w.prepared)" -ForegroundColor Yellow
        if ([int]$b.stale -gt 0) { Write-Host "    (plus $($b.stale) waiting card(s) left by earlier sessions; those do not hold it)" -ForegroundColor DarkYellow }
        if ($runs.Count -eq 0 -and $held -eq 0) {
          Write-Host "    nothing is holding it: it is reaped 15 min after going idle. Re-run then, or with -Force." -ForegroundColor Yellow
        }
      }
    }
    if ($running.Count -gt 0) {
      $ids = ($running | ForEach-Object { "#$($_.id) $($_.kind)" }) -join ", "
      Write-Host "  running user_chrome runs: $ids" -ForegroundColor Yellow
    }
    Write-Host "Wait for it to finish, or re-run with -Force." -ForegroundColor Yellow
    exit 2
  }
}

$before = git rev-parse HEAD
Write-Host "==> git pull --ff-only"
git pull --ff-only
if ($LASTEXITCODE -ne 0) { throw "git pull failed" }

# `npm ci` wipes node_modules first. On Windows that fails with EPERM while the server is running,
# because the native modules it has loaded (better-sqlite3, next-swc, node-pty) are locked files -
# and by then half of node_modules is already gone (2026-09-11). So: only reinstall when the
# lockfile actually changed (or node_modules is missing), and stop the server first so the locks
# are released. A deploy that does not touch dependencies keeps the old server up until the build
# has succeeded.
git diff --quiet $before HEAD -- package-lock.json
$lockChanged = ($LASTEXITCODE -ne 0)
$needInstall = $lockChanged -or -not (Test-Path (Join-Path $Root "node_modules/next/package.json"))
$stopped = $false
if ($needInstall) {
  Write-Host "==> dependencies changed (or node_modules missing): pm2 stop sortie, then npm ci"
  pm2 stop sortie | Out-Null
  $stopped = $true
  npm ci
  if ($LASTEXITCODE -ne 0) { throw "npm ci failed - server is STOPPED. Fix the install (re-run npm ci), then: pm2 restart sortie --update-env" }
} else {
  Write-Host "==> package-lock.json unchanged since $($before.Substring(0,7)): skipping npm ci"
}

Write-Host "==> npm run build"
npm run build
if ($LASTEXITCODE -ne 0) {
  if ($stopped) { throw "build failed - server is STOPPED (dependencies were reinstalled). Fix the build, then: pm2 restart sortie --update-env" }
  throw "build failed - server NOT restarted. .next may be partially overwritten: fix the build and re-run."
}

Write-Host "==> pm2 restart sortie"
pm2 restart sortie --update-env
if ($LASTEXITCODE -ne 0) { throw "pm2 restart failed (is the app registered? pm2 start ops\windows\ecosystem.config.cjs --only sortie)" }

# Readiness = the server answers at all. Any HTTP status counts, 401 included: since accounts
# (2026-09-13) every API route wants a principal, and the internal token only resolves to the
# owner account — on a box where nobody has registered yet, a fresh server answers 401 to the
# status probe while being perfectly healthy (seen on the accounts deploy itself).
function Test-ServerUp($url) {
  try { Invoke-RestMethod -Uri $url -TimeoutSec 5 -Headers (Get-AuthHeaders) | Out-Null; return $true }
  catch { if ($_.Exception.Response) { return $true } else { return $false } }
}
$deadline = (Get-Date).AddSeconds(60)
$ok = $false
do {
  Start-Sleep -Seconds 2
  $ok = Test-ServerUp "$Base/api/executor/status"
} until ($ok -or (Get-Date) -gt $deadline)
if (-not $ok) { throw "server did not answer on $Base within 60s - check: pm2 logs sortie" }

$sha = git rev-parse --short HEAD
$subject = git log -1 --pretty=%s
Write-Host "==> deployed $sha : $subject" -ForegroundColor Green
